# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fe_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=128)),
                ('numero', models.CharField(max_length=32)),
                ('complemento', models.CharField(blank=True, max_length=32, null=True)),
                ('bairro', models.CharField(max_length=56)),
                ('cidade', models.CharField(max_length=56)),
                ('estado', models.CharField(max_length=2)),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fe_core.Entity')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
